CREATE TABLE IF NOT EXISTS "error_events" (
  "id" varchar(255) PRIMARY KEY,
  "project_id" varchar(255),
  "issue_id" varchar(255),
  "message" text,
  "stack" text,
  "error_type" varchar(255),
  "category" varchar(255),
  "severity" varchar(255),
  "fingerprint" varchar(255),
  "url" text,
  "browser" varchar(255),
  "os" varchar(255),
  "user_agent" text,
  "framework" varchar(255),
  "release" varchar(255),
  "environment" varchar(255),
  "user_context" text,
  "metadata" text,
  "timestamp" varchar(255),
  "created_at" timestamp not null default CURRENT_TIMESTAMP,
  "updated_at" timestamp
);
